Feature navigation
patriciachrysy/Web-Developers-Booking-App pull request #17
Opened 2024-02-01 06:12 UTC by AbuTalha3

**In this PR i have**
-Create the `navbar` with all required buttons
-Added a header and footer.
- Added a logo and title of App

![image](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/127955219/be594537-dfaf-4fca-a96f-4b371bae148f)

2024-02-01 06:14 UTC, AbuTalha3 commented
@richie1988  Please have a look at it. Regards

2024-02-01 09:48 UTC, richie1988 requested changes
Hi @AbuTalha3 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

REDO

Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

Required Changes ♻️
Check the comments under the review.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-01 09:48 UTC, richie1988 commented on react-front-end/src/components/NavBar/Navbar.css
> +}
I would recommend you reduce the size of the social icon and reduce the size on the mobile version to make it responsive cause there is a width of px i would also recommend you use % instead of px cause px is not easy to reduce the size of mobile screen and on mobile version
![chrome_E1wK9j11bD](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/cd70f8a2-5fa6-4144-b40a-4d6e902788eb)
![chrome_Iez2UAWunO](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/f0f5dfd9-ac4d-4edf-9bbe-7125ffa86d74)
![ppDJI0d77w](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/2f2c0c8f-65b4-4408-b80a-adee1aefbded)
![ShareX_d0toc3Udr3](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/848a769d-9352-4527-a383-685a5c464994)

2024-02-01 09:51 UTC, richie1988 commented on react-front-end/src/components/NavBar/Navbar.css
> +}
I suggest that you follow the same approach you did for the budget app cause we had a navbar that had mobile screen menu i think it would be better.

2024-02-02 15:42 UTC, richie1988 requested changes
Hi @AbuTalha3 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

REDO

Highlights

✅ Good implementation of the principle of separating concerns.

Required Changes ♻️
![ShareX_facQJoxgR0](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/6024d17c-55c6-4c51-b143-462de97a2bc7)


Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
![chrome_Iez2UAWunO](https://github.com/patriciachrysy/Web-Developers-Booking-App/assets/97953658/87f87763-2e6f-4e34-a819-ed9df2565b12)
![Uploading chrome_1OCWQYdc5F.png…]()

2024-02-02 17:19 UTC, richie1988 approved these changes
## Approved
Hi @AbuTalha3 

WELL DONE
Good job 
You still need to work on some issues to go to the next project, but you are almost there!

Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.


Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-02 17:22 UTC, merged